### ISSUE TITLE
为什么ip地址不能输入机器名称

### ISSUE THREAD

**Issue by ghd258** [yswenli/WebRedisManager#12]
为什么ip地址不能输入机器名称，以及建立的连接无法修改 只能删除后从新建立

**Comment by ghd258** [comment]
https://gitee.com/MaxBill/RedisPlus  这个更强大

**Comment by yswenli** [comment]
为什么ip地址不能输入机器名称，以及建立的连接无法修改 只能删除后从新建立?
不能输入机器名称？这个你绑了dns么~
建立的连接无法修改？只要名称一样，修改连接内容就行了，类似于addorupdate~

**Comment by ghd258** [comment]
个人建议参考这个工具 RedisPlus   功能非常强大 ；批量删除等操作方便

**Comment by yswenli** [comment]
这个新版的也有~




------------------ 原始邮件 ------------------
发件人: "ghd258"<notifications@github.com>; 
发送时间: 2019年8月5日(星期一) 上午10:07
收件人: "yswenli/WebRedisManager"<WebRedisManager@noreply.github.com>; 
抄送: "WALL·E"<wenguoli_520@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [yswenli/WebRedisManager] 为什么ip地址不能输入机器名称 (#12)




个人建议参考这个工具 RedisPlus   功能非常强大 ；批量删除等操作方便
