### ISSUE TITLE
希望option name改成图标，现有option name改成全局key值，进入数据库key值自动带入输入的值

### ISSUE THREAD

**Issue by yijia0404** [yswenli/WebRedisManager#18]

**Comment by yswenli** [comment]
不好意思，没明白意思~

**Comment by yijia0404** [comment]
就是提供类似redis desktop manager，全局的key值检索。现在每次点开新的库，key值就会重置，但是有时很多库都只是查一个key，如果一开始输入一个key，后面打开相应的库，直接就按这个key检索，就非常好了。

**Comment by yswenli** [comment]
明白你的意思了，optionName是查多个配置的，有的管理几十个集群，找起来不方便。 
另外单库模糊查就非常危险了，这种全局查太危险，有人就把集群查挂过，如无必要还是不能放
