### ISSUE TITLE
页面偶尔会无相应的问题

### ISSUE THREAD

**Issue by Holo-k** [yswenli/WebRedisManager#21]
非常感谢开发此工具，Web操作给我带来了很多的便利。我在服务器上使用内置的Kestrel 作为托管服务器并使用window service作为后台进程，但是我发现程序在运行的久后会出现无相应的问题，目前我的Redis版本是3.2。

**Comment by yswenli** [comment]
这个无需使用Kestrel，本身就含有SAEA.HttpServer，如果是windows service可参考https://github.com/yswenli/SAEA/tree/master/Src/SAEA.Mvc.ServiceTest

**Comment by Holo-k** [comment]
> 这个无需使用Kestrel，本身就含有SAEA.HttpServer，如果是windows service可参考https://github.com/yswenli/SAEA/tree/master/Src/SAEA.Mvc.ServiceTest

我把整个程序作为windows service部署，会不会SAEA.HttpServer不适合长时间运行?

**Comment by yswenli** [comment]
可以长时间运行的，这个我自已也用，经常挂着十天半个月的没有什么问题的~
你可以使用最新版来试试~
