### ISSUE TITLE
似乎不支持集群

### ISSUE THREAD

**Issue by 16it** [yswenli/WebRedisManager#3]
我Redis部署的集群，用这个管理连不上，不知道是没用对还是咋滴。

**Comment by yswenli** [comment]
使用最新版后，仔细检查网络，添加redis之前请先ping一下地址或者telnet 一下ip port看是否通畅~

**Comment by 16it** [comment]
谢谢，估计是我太菜，或者我是跟我们的集群模式有关，使用java版的treesoft就没问题。
