### ISSUE TITLE
查询数据服务端返回空指针，前端页面js错误

### ISSUE THREAD

**Issue by czd890** [yswenli/WebRedisManager#5]
问题一：
在命令行模式页面直接执行命令能查询出来，在keys列表scan出现错误
![image](https://user-images.githubusercontent.com/4011549/55768743-a88bf800-5ab0-11e9-9344-ed6668750499.png)

问题二：
core版本建议publish 把依赖包全部打包进来。
![image](https://user-images.githubusercontent.com/4011549/55768959-83e45000-5ab1-11e9-97a7-3f948a692a4c.png)

**Comment by yswenli** [comment]
这个对比较老版本的redis支持可能会有些问题

**Comment by yswenli** [comment]
core的全包比较大，github一次最多只能传10M~

**Comment by czd890** [comment]
可以考虑使用ci/cd来构建，readme可以加一下最低支持版本😂
