### ISSUE TITLE
添加或编辑redis数据value控件改为textarea操作起来会方便

### ISSUE THREAD

**Issue by tianpy** [yswenli/WebRedisManager#6]
![image](https://user-images.githubusercontent.com/13298124/56075754-342bbe80-5dfa-11e9-84c3-7411eff96cbf.png)

**Comment by yswenli** [comment]
不错的建议~

**Comment by smartYUUY** [comment]
添加数据时特殊字符有问题
![image](https://user-images.githubusercontent.com/24379178/62201749-9533ce00-b3ba-11e9-9661-a9f2790bf53a.png)
![image](https://user-images.githubusercontent.com/24379178/62201806-aaa8f800-b3ba-11e9-80fd-e54573b12d9c.png)
![image](https://user-images.githubusercontent.com/24379178/62201982-fcea1900-b3ba-11e9-908a-cdddbeb270c8.png)
![image](https://user-images.githubusercontent.com/24379178/62202009-0bd0cb80-b3bb-11e9-8013-1bd42903e436.png)
![image](https://user-images.githubusercontent.com/24379178/62201846-c01e2200-b3ba-11e9-844e-9fa88483a63d.png)
![image](https://user-images.githubusercontent.com/24379178/62201910-e217a480-b3ba-11e9-80b7-dd6fc3d0f37e.png)

**Comment by yswenli** [comment]
请使用新版本试试看~



------------------ 原始邮件 ------------------
发件人: "yulei"<notifications@github.com>; 
发送时间: 2019年7月31日(星期三) 下午5:46
收件人: "yswenli/WebRedisManager"<WebRedisManager@noreply.github.com>; 
抄送: "WALL·E"<wenguoli_520@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [yswenli/WebRedisManager] 添加或编辑redis数据value控件改为textarea操作起来会方便 (#6)




添加数据时特殊字符有问题
