### ISSUE TITLE
最新版本用16379一直无法访问

### ISSUE THREAD

**Issue by XLiming** [yswenli/WebRedisManager#9]
浏览器一直转圈圈，无法访问，怎么处理呢？

**Comment by XLiming** [comment]
用的是.net core 2.1 runtime 可以吗？

**Comment by XLiming** [comment]
旧版本4.0.0.1可以访问，但是提示 →_→，出错了：Object reference not set to an instance of an object.

**Comment by yswenli** [comment]
.net core 2.0~

**Comment by yswenli** [comment]
另外你检查一下16379这个端口是否已被占用~

**Comment by XLiming** [comment]
不行哦，yum install dotnet-hosting-2.0.6，2.0版本，也是无法运行呢。

**Comment by XLiming** [comment]
端口正常以前版本可以再windows打开，4.3.2.5新版本windows也不行

**Comment by XLiming** [comment]
[root@iZbp13ecl54zrh28qf7i49Z WebRedisManager]# dotnet --info                   
Host (useful for support):
  Version: 2.1.10
  Commit:  9013a2af4b

.NET Core SDKs installed:
  No SDKs were found.

.NET Core runtimes installed:
  Microsoft.NETCore.App 2.0.6 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
[root@iZbp13ecl54zrh28qf7i49Z WebRedisManager]# dotnet SAEA.WebRedisManager.dll
2019-04-20 13:23:29.724  WebRedisManager已启动
2019-04-20 13:23:29.727  请在浏览器上打开：http://localhost:16379/
2019-04-20 13:23:29.727  回车退出服务...

**Comment by yswenli** [comment]
请下载使用最新源码或Release包，linux目录大小写敏感问题已修复~
